/**
 * 
 * CHECKOUTSUCCESS COMPONENT
 * This component is responsible for providing positive feedback to the user after a successful transaction.
 * Key Functionalities:
 * - Order Confirmation: Receives and displays the unique Transaction ID (orderId) generated by Firestore.
 * - Visual Feedback: Uses high-impact visual elements like icons and decorative boxes to enhance the "Success" state experience.
 * - Post-Purchase Navigation: Offers a clear call to action (CTA) to redirect the user back to the main catalog.
 * - UX/UI: Implements a clean, centered layout using Chakra UI's VStack and Container for a professional finish.
 *
 * 
 * COMPONENTE CHECKOUTSUCCESS
 * Este componente se encarga de proporcionar feedback positivo al usuario tras una transacción exitosa.
 * Funcionalidades Clave:
 * - Confirmación de Orden: Recibe y muestra el ID de transacción único (orderId) generado por Firestore.
 * - Feedback Visual: Utiliza elementos visuales de alto impacto como íconos y cajas decorativas para mejorar la experiencia del estado de "Éxito".
 * - Navegación Post-Compra: Ofrece una llamada a la acción (CTA) clara para redirigir al usuario de vuelta al catálogo principal.
 * - UX/UI: Implementa un diseño limpio y centrado utilizando VStack y Container de Chakra UI para un acabado profesional.
 */


// @ts-ignore
import { Box, Heading, Text, Button, VStack, Container, Icon } from '@chakra-ui/react';
// @ts-ignore
import { CheckCircleIcon } from '@chakra-ui/icons';
import { Link } from 'react-router-dom';

interface CheckoutSuccessProps {
    orderId: string;
}

const CheckoutSuccess = ({ orderId }: CheckoutSuccessProps) => {
    return (
        <Container maxW="container.md" py={20}>
            <VStack 
                gap={6} 
                p={10} 
                borderWidth="1px" 
                borderRadius="2xl" 
                boxShadow="xl" 
                bg="white"
                textAlign="center"
            >
                <Icon as={CheckCircleIcon} w={20} h={20} color="green.500" />
                <Heading size="xl">¡Gracias por tu compra!</Heading>
                <Text fontSize="lg">
                    Tu pedido de fragancias ha sido procesado con éxito. 
                    Tu código de seguimiento es:
                </Text>
                <Box bg="teal.50" p={6} borderRadius="md" w="full" border="2px dashed" borderColor="teal.200">
                    <Text fontWeight="bold" fontSize="2xl" color="teal.600">
                        {orderId}
                    </Text>
                </Box>
                <Button 
    as={Link} 
    {...({ to: "/" } as any)} 
    colorScheme="teal" 
    size="lg" 
    w="full"
>
    Seguir explorando perfumes
</Button>
            </VStack>
        </Container>
    );
};

export default CheckoutSuccess;